name: node_app 

on:  # Указал на какие события будет срабатывать CI/CD
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest  # Указал на какой операционной системе будет происходит событие
    
    steps:
      - # Использую уже готовое событие для клонирования кода из своего репозитория
        name: Checkout
        uses: actions/checkout@v6
      - # Использую уже готовое событие для входа в DockerHub через токен
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # Использую уже готовое событие для создания экземпляра build kit builder
        name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - # Использую уже готовое событие для сборки образа и отправки его на DockerHub с помощью тега clockbox
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
